'''arr=map(int, input().split())
n=list(arr)
m_list=sorted(n)
o=set(m_list)
print("Second Smallest", m[1])
print("Second largest", o[-2])'''
array=map(int, input().split())
n=list(set(array))
print("Second Smallest", n[1])
print("Second largest", n[1])
